### ISSUE TITLE
Can we save the converted table into CSV format?

### ISSUE THREAD

**Issue by ssun1116** [robertaboukhalil/oct4th#2]
Dear development team,

Thank you for developing such a wonderful tool! 
I was surprised by its conciseness and convenience in addressing long-term issues in bioinformatics.

I've observed that the tool currently supports output only in Excel format.
While this remains convenient, are there any plans to include the option to save the output in CSV or other table formats?
Introducing such flexibility would greatly enhance the tool's usability for diverse applications! :)

Thanks in advance, 
Seoyeon

**Comment by robertaboukhalil** [comment]
Thanks @ssun1116! The issue with an output in CSV format would be that it would just return your original CSV. As far as I know, there's nothing that can be done in the CSV itself to prevent Excel from interpreting it as a date.
